version: '3.8'
services:
  umlautadaptarr:
    #uncomment this to get the development branch
    #build: https://github.com/PCJones/UmlautAdaptarr.git#develop
    build: https://github.com/PCJones/UmlautAdaptarr.git#master
    image: umlautadaptarr
    restart: unless-stopped
    ports:
      - "5005:5005" # can be removed if you use the recommended prowlarr+proxy configuration 
      - "5006:5006" # can be removed if you use the alternative, non-proxy configuration
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=false
      - SONARR__HOST=http://localhost:8989
      - SONARR__APIKEY=APIKEY
      - RADARR__ENABLED=false
      - RADARR__HOST=http://localhost:7878
      - RADARR__APIKEY=APIKEY
      - READARR__ENABLED=false
      - READARR__HOST=http://localhost:8787
      - READARR__APIKEY=APIKEY
      - LIDARR__ENABLED=false
      - LIDARR__HOST=http://localhost:8686
      - LIDARR__APIKEY=APIKEY
      ### example for multiple instances of same type
      #- SONARR__0__NAME=NAME 1 (optional)
      #- SONARR__0__ENABLED=false
      #- SONARR__0__HOST=http://localhost:8989
      #- SONARR__0__APIKEY=APIKEY
      #- SONARR__1__NAME=NAME 2 (optional)
      #- SONARR__1__ENABLED=false
      #- SONARR__1__HOST=http://localhost:8989
      #- SONARR__1__APIKEY=APIKEY

      ### Advanced options (with default values))
      #- IpLeakTest__Enabled=false
      #- SETTINGS__IndexerRequestsCacheDurationInMinutes=12
      #- Kestrel__Endpoints__Http__Url=http://[::]:8080
      
