version: '3.8'
services:
  umlautadaptarr:
    build: https://github.com/PCJones/UmlautAdaptarr.git#master
    image: umlautadaptarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - SONARR_HOST="http://sonarr:8989"
      - SONARR_API_KEY="API_KEY"
    ports:
      - "5005:5005" 
