version: '3.8'
services:
  umlautadaptarr:
    build: https://github.com/PCJones/UmlautAdaptarr.git#master
    image: umlautadaptarr
    restart: unless-stopped
    networks:
      - local
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}

    environment:
      SONARR_HOST: "http://sonarr:8989"
      SONARR_API_KEY: ${SONARR_API_KEY}
    ports:
      - "5005:5005" 
