version: '3.8'
services:
  umlautadaptarr:
    #uncomment this to get the development branch
    #build: https://github.com/PCJones/UmlautAdaptarr.git#develop
    build: https://github.com/PCJones/UmlautAdaptarr.git#master
    image: umlautadaptarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=false
      - SONARR__HOST=http://localhost:8989
      - SONARR__APIKEY=APIKEY
      - RADARR__ENABLED=false
      - RADARR__HOST=http://localhost:7878
      - RADARR__APIKEY=APIKEY
      - READARR__ENABLED=false
      - READARR__HOST=http://localhost:8787
      - READARR__APIKEY=APIKEY
      - LIDARR__ENABLED=false
      - LIDARR__HOST=http://localhost:8686
      - LIDARR__APIKEY=APIKEY
      #- Proxy__Enabled: false
      #- Proxy__Address: http://yourproxyaddress:port
      #- Proxy__Username: your_proxy_username
      #- Proxy__Password: your_proxy_password
      #- Proxy__BypassOnLocal: true (set to false to not bypass local IP addresses)