version: '3.8'
services:
  umlautadaptarr:
    #uncomment this to get the development branch
    #build: https://github.com/PCJones/UmlautAdaptarr.git#develop
    build: https://github.com/PCJones/UmlautAdaptarr.git#master
    image: umlautadaptarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - SONARR_ENABLED=false
      - SONARR_HOST=http://localhost:8989
      - SONARR_API_KEY=API_KEY
      - RADARR_ENABLED=false
      - RADARR_HOST=http://localhost:7878
      - RADARR_API_KEY=API_KEY
      - READARR_ENABLED=false
      - READARR_HOST=http://localhost:8787
      - READARR_API_KEY=API_KEY
      - LIDARR_ENABLED=false
      - LIDARR_HOST=http://localhost:8686
      - LIDARR_API_KEY=API_KEY